FROM node:20

WORKDIR /app

COPY package*.json /app/

ENV NODE_ENV=production

RUN npm install

COPY . /app

EXPOSE 3000

CMD ["npm", "start"]
FROM node:20

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app

EXPOSE 3000

CMD ["npm", "start"]